[package]
name = "penrose_ui"
version = "0.1.3"
edition = "2021"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/penrose/crates/penrose_ui"
documentation = "https://docs.rs/penrose_ui"
readme = "README.md"
description = "UI elements for the penrose window manager library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.15.6", features = ["xcb"] }
pangocairo = { version = "0.15.1" }
pango = { version = "0.15.6" }
penrose = { version = "0.3", path = "../../" }
tracing = { version = "0.1", features = ["attributes", "log"] }
thiserror = "1.0.37"
x11rb = { version = "0.11", features = ["randr", "render"] }
